### PR TITLE
Add a parameter to make rbenv configuration optional

### LINKED ISSUE #202: managing /gitlab-shell/hooks/update breaks editing via web interface
Adding the below hooks/update file in to gitlab-shell breaks editing files via gitlab's web interface.

Removing the file / commenting out the block in install.pp fixes the issue and doesn't seem to break anything else?

install.pp:140
```
  file { "${git_home}/gitlab-shell/hooks/update":
    ensure  => present,
    content => template('gitlab/update.erb'),
    mode    => '0775',
    require => File["${git_home}/gitlab-shell/config.yml"],
  }
```

GitLab 7.3.2
GitLab Shell 2.0.1
GitLab API v3
Ruby 2.1.2p95
Rails 4.1.1

### PR DESCRIPTION
**Pull request by alexcern**
This incidently provides a workaround for #172.
This uses a different method to change ruby path in
gitlab-shell hooks when rbenv is used and hence
fixes #202 as well.

### CODE REVIEW

**Comment by alexcern** [comment]
Hum, looks like the automatic build now fails because metadata-json-lint has suddenly become more strict about license strings since a few days and "GPLv3" is not considered valid anymore. I'm not sure I should touch license information though, so I'm leaving it as it is...

**Comment by igalic** [comment]
should be fixed in #205

**Comment by alexcern** [comment]
Thanks! Rebased the PR, tests are OK now.

**Comment by igalic** [comment]
@sbadia @andschwa thoughts?

**Comment by andschwa** [comment]
Yes, I thinking being able to turn it off is a good thing. I should have included that from the beginning!

**Comment by sbadia** [comment]
Hi, sorry for the delay… thanks @alexcern for this PR, it's ok for me (and for others also visibly :p), beaker is happy. Thanks all!

```
~/d/g/s/puppet-gitlab git:cernops-feature/rbenv_optional ❯❯❯ BEAKER_destroy=no rspec spec/acceptance                 ◼ 
Beaker::Hypervisor, found some vagrant boxes to create
==> debian-73-x64: VM not created. Moving on...
Bringing machine 'debian-73-x64' up with 'virtualbox' provider...
==> debian-73-x64: Importing base box 'debian-73-x64-nocm'...
==> debian-73-x64: Matching MAC address for NAT networking...
==> debian-73-x64: Setting the name of the VM: defaultyml_debian-73-x64_1426772305220_5239
==> debian-73-x64: Fixed port collision for 22 => 2222. Now on port 2200.
==> debian-73-x64: Clearing any previously set network interfaces...
==> debian-73-x64: Preparing network interfaces based on configuration...
    debian-73-x64: Adapter 1: nat
    debian-73-x64: Adapter 2: hostonly
==> debian-73-x64: Forwarding ports...
    debian-73-x64: 22 => 2200 (adapter 1)
==> debian-73-x64: Running 'pre-boot' VM customizations...
==> debian-73-x64: Booting VM...
==> debian-73-x64: Waiting for machine to boot. This may take a few minutes...
    debian-73-x64: SSH address: 127.0.0.1:2200
    debian-73-x64: SSH username: vagrant
    debian-73-x64: SSH auth method: private key
    debian-73-x64: Warning: Connection timeout. Retrying...
==> debian-73-x64: Machine booted and ready!
==> debian-73-x64: Checking for guest additions in VM...
==> debian-73-x64: Setting hostname...
==> debian-73-x64: Configuring and enabling network interfaces...
==> debian-73-x64: Mounting shared folders...
    debian-73-x64: /vagrant => /home/sbadia/dev/github.com/sbadia/puppet-gitlab/.vagrant/beaker_vagrant_files/default.yml
Allocated a PTY on 10.255.132.116 for "sudo su -c \"cp -r .ssh /root/.\""
Allocated a PTY on 10.255.132.116 for "sudo su -c \"sed -ri 's/^#?PermitRootLogin no|^#?PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config\""
Allocated a PTY on 10.255.132.116 for "sudo su -c \"service ssh restart\""
localhost $ scp /home/sbadia/dev/github.com/sbadia/puppet-gitlab debian-73-x64:/etc/puppet/modules {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "bundle", "spec", "tests", "log", ".", ".."]}

gitlab class
  default parameters
localhost $ scp /tmp/beaker20150319-18781-tg53sg debian-73-x64:/tmp/apply_manifest.pp.j6gOOb {:ignore => }
localhost $ scp /tmp/beaker20150319-18781-1wc8jh5 debian-73-x64:/tmp/apply_manifest.pp.JNIT2l {:ignore => }
    should work with no errors

Finished in 16 minutes 11 seconds (files took 1 minute 11.46 seconds to load)
1 example, 0 failures
```

**Pull request merged**
